<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <LibraryPath>$(ProjectDir);$(LibraryPath)</LibraryPath>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <Link>
      <AdditionalDependencies>USB340HID61.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
    <PostBuildEvent>
      <Command>xcopy /y "$(ProjectDir)USB340HID61.dll" "$(SolutionDir)x64\Debug\"
xcopy /y "$(TargetDir)$(TargetName).exe" "$(SolutionDir)x64\Debug\"</Command>
    </PostBuildEvent>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>